version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dentalsanfelipe
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dental_sanfelipe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/db/dental_sanfelipe.sql:/docker-entrypoint-initdb.d/dental_sanfelipe.sql
volumes:
  mysql_data:
